highlighter: pygments
name: Atomium
description: TODO
# url: http://WegenenVerkeer.github.com/atomium/
url: http://localhost:4000
markdown: kramdown

repository: https://github.com/WegenenVerkeer/atomium
version: 0.1.1-SNAPSHOT

collections:
  docs:
    output: true